# -*- coding: utf-8 -*-
"""aula001(arvore).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtJ5X8NK5R4GiBHFFBjYT8a8wryODiy-
"""

# -*- coding: utf-8 -*-
"""Aula001-VersaoMinimaParaTrabalho-Aprovacao-Alunos.ipynb"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree

# ==========================================================
# 1) Leitura do dataset (Google Sheets - aba correta)
# ==========================================================

SHEET_ID = "1PiScPawV8qN_dzx3JqHWjTKYae8q07wm"
GID = "1334296780"  # aba correta

url_csv = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&gid={GID}"

df = pd.read_csv(url_csv)

print("Colunas lidas:", list(df.columns))
display(df.head())

# ==========================================================
# 2) Definição das variáveis
# ==========================================================

FEATURES = [
    "horas_estudo_semana",
    "faltas",
    "media_simulados"
]

TARGET = "aprovado"

# Garantir tipo numérico
for col in FEATURES:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce")

# Remover linhas inválidas
df = df.dropna(subset=FEATURES + [TARGET]).copy()

print("\nDistribuição do target:")
print(df[TARGET].value_counts())
print("Total linhas válidas:", len(df))

# ==========================================================
# 3) Split Estratificado
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    df[FEATURES].values,
    df[TARGET].values,
    test_size=0.20,
    random_state=42,
    stratify=df[TARGET].values
)

print("\nTreino:", len(X_train), "| Teste:", len(X_test))

# ==========================================================
# 4) Random Forest
# ==========================================================

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("\n=== Random Forest ===")
print("Acurácia:", accuracy_score(y_test, y_pred_rf))
print("\nRelatório:")
print(classification_report(y_test, y_pred_rf))
print("Matriz de confusão (real x previsto):")
print(confusion_matrix(y_test, y_pred_rf))

# ==========================================================
# 5) Importância das variáveis
# ==========================================================

print("\nImportância das variáveis:")
importances = rf.feature_importances_

for f, imp in sorted(zip(FEATURES, importances), key=lambda x: x[1], reverse=True):
    print(f"{f}: {round(imp,4)}")

# ==========================================================
# 6) Árvore de Decisão
# ==========================================================

tree = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

print("\n=== Árvore de Decisão ===")
print("Acurácia:", accuracy_score(y_test, y_pred_tree))
print("\nRelatório:")
print(classification_report(y_test, y_pred_tree))
print("Matriz de confusão (real x previsto):")
print(confusion_matrix(y_test, y_pred_tree))

# ==========================================================
# 7) Visualização da Árvore
# ==========================================================

plt.figure(figsize=(14, 8))
plot_tree(
    tree,
    feature_names=FEATURES,
    class_names=["Reprovado (0)", "Aprovado (1)"],
    filled=True,
    rounded=True,
    impurity=True
)
plt.title("Árvore de Decisão — Previsão de Aprovação")
plt.show()