# -*- coding: utf-8 -*-
"""aula006(regras).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkjYFUO0AmTCk37iuAFFSvAxKe8LfZ6i
"""

# =========================================
# PRISM - GERAÇÃO DE REGRAS
# =========================================

import pandas as pd

# =========================================
# 1. DATASET
# =========================================
data = [
['young','myope','no','reduced','none'],
['young','myope','no','normal','soft'],
['young','myope','yes','reduced','none'],
['young','myope','yes','normal','hard'],
['young','hypermetrope','no','reduced','none'],
['young','hypermetrope','no','normal','soft'],
['young','hypermetrope','yes','reduced','none'],
['young','hypermetrope','yes','normal','hard'],

['pre-presbyopic','myope','no','reduced','none'],
['pre-presbyopic','myope','no','normal','soft'],
['pre-presbyopic','myope','yes','reduced','none'],
['pre-presbyopic','myope','yes','normal','hard'],
['pre-presbyopic','hypermetrope','no','reduced','none'],
['pre-presbyopic','hypermetrope','no','normal','soft'],
['pre-presbyopic','hypermetrope','yes','reduced','none'],
['pre-presbyopic','hypermetrope','yes','normal','none'],

['presbyopic','myope','no','reduced','none'],
['presbyopic','myope','no','normal','none'],
['presbyopic','myope','yes','reduced','none'],
['presbyopic','myope','yes','normal','hard'],
['presbyopic','hypermetrope','no','reduced','none'],
['presbyopic','hypermetrope','no','normal','soft'],
['presbyopic','hypermetrope','yes','reduced','none'],
['presbyopic','hypermetrope','yes','normal','none'],
]

columns = ['age','spectacle','astigmatism','tear','classe']
df_original = pd.DataFrame(data, columns=columns)

# =========================================
# 2. FUNÇÕES PRISM
# =========================================
def melhor_atributo(df, target_class, usados):
    melhor = None
    melhor_prob = -1

    for col in df.columns[:-1]:
        if col in usados:
            continue

        for val in df[col].unique():
            subset = df[df[col] == val]

            if len(subset) == 0:
                continue

            prob = len(subset[subset['classe'] == target_class]) / len(subset)

            if prob > melhor_prob:
                melhor_prob = prob
                melhor = (col, val)

    return melhor


def gerar_regras(df, target_class):
    regras = []
    df_work = df.copy()

    while len(df_work[df_work['classe'] == target_class]) > 0:
        condicoes = []
        usados = set()
        subset = df_work.copy()

        while True:
            melhor = melhor_atributo(subset, target_class, usados)

            if melhor is None:
                break

            col, val = melhor
            condicoes.append((col, val))
            usados.add(col)

            subset = subset[subset[col] == val]

            # regra perfeita
            if len(subset) > 0 and all(subset['classe'] == target_class):
                break

        if len(subset) == 0:
            break

        regras.append(condicoes)

        # remover exemplos cobertos
        for col, val in condicoes:
            df_work = df_work[df_work[col] != val]

    return regras

# =========================================
# 3. GERAR REGRAS
# =========================================
classes = df_original['classe'].unique()

todas_regras = {}

for c in classes:
    regras = gerar_regras(df_original, c)
    todas_regras[c] = regras

# =========================================
# 4. MOSTRAR REGRAS
# =========================================
print("=== REGRAS GERADAS ===\n")

for classe, regras in todas_regras.items():
    print(f"Classe: {classe}")

    for i, regra in enumerate(regras):
        cond = " AND ".join([f"{c}={v}" for c,v in regra])
        print(f"R{i+1}: IF {cond} THEN classe={classe}")

    print()

# =========================================
# 5. CLASSIFICADOR BASEADO EM REGRAS
# =========================================
def prever(exemplo):
    for classe, regras in todas_regras.items():
        for regra in regras:
            if all(exemplo[c] == v for c,v in regra):
                return classe
    return "desconhecido"

# =========================================
# 6. TESTE
# =========================================
exemplo = {
    'age': 'young',
    'spectacle': 'myope',
    'astigmatism': 'yes',
    'tear': 'normal'
}

print("Exemplo:", exemplo)
print("Classe prevista:", prever(exemplo))