# -*- coding: utf-8 -*-
"""aula003(KNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaO1_e6UQmUBd1Bjc-fydK1NrBMoEonL
"""

# =========================================
# KNN + KNN PONDERADO + CENTROIDE
# =========================================

import pandas as pd
import numpy as np

# =========================================
# 1. DATASET (DO SLIDE)
# =========================================
data = [
[2, 9, 'Vermelho'],
[6.5, 6, 'Azul'],
[6, 2.5, 'Azul'],
[5.5, 8, 'Azul'],
[5, 5, 'Azul'],
[4, 10, 'Vermelho'],
[7, 4, 'Azul'],
[4, 7.5, 'Azul'],
[3.9, 5.8, 'Vermelho'],
[4.5, 7.3, 'Azul'],
]

df = pd.DataFrame(data, columns=['x1', 'x2', 'classe'])

# =========================================
# 2. PONTO A CLASSIFICAR
# =========================================
ponto = np.array([4.2, 9.0])

# =========================================
# 3. DISTÂNCIA EUCLIDIANA
# =========================================
def distancia(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

# calcular distâncias
distancias = []

for i, row in df.iterrows():
    p = np.array([row['x1'], row['x2']])
    d = distancia(ponto, p)

    distancias.append((i, d, row['classe']))

# ordenar
distancias.sort(key=lambda x: x[1])

print("=== DISTÂNCIAS ===")
for i, d, c in distancias:
    print(f"Ponto {i+1} -> Distância: {d:.4f} | Classe: {c}")

# =========================================
# 4. KNN (k=3)
# =========================================
k = 3
vizinhos = distancias[:k]

print("\n=== KNN (k=3) ===")
contagem = {}

for _, _, c in vizinhos:
    contagem[c] = contagem.get(c, 0) + 1

for c in contagem:
    print(f"{c}: {contagem[c]} votos")

classe_knn = max(contagem, key=contagem.get)
print("Classe final (KNN):", classe_knn)

# =========================================
# 5. KNN PONDERADO (1/dist)
# =========================================
print("\n=== KNN PONDERADO ===")

pesos = {}

for _, d, c in vizinhos:
    peso = 1 / d
    pesos[c] = pesos.get(c, 0) + peso

for c in pesos:
    print(f"{c}: {pesos[c]:.4f}")

classe_ponderado = max(pesos, key=pesos.get)
print("Classe final (ponderado):", classe_ponderado)

# =========================================
# 6. NEAREST CENTROID
# =========================================
print("\n=== NEAREST CENTROID ===")

centroides = {}

for c in df['classe'].unique():
    subset = df[df['classe'] == c]
    centroid = np.array([subset['x1'].mean(), subset['x2'].mean()])
    centroides[c] = centroid

# calcular distância até centroides
dist_centroides = {}

for c, centro in centroides.items():
    d = distancia(ponto, centro)
    dist_centroides[c] = d
    print(f"{c}: centro={centro} | distância={d:.4f}")

classe_centroide = min(dist_centroides, key=dist_centroides.get)
print("Classe final (centroide):", classe_centroide)